# Generated by Django 3.1.1 on 2020-09-17 16:52

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hotel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=255)),
                ('image', models.ImageField(null=True, upload_to=api.models.image_file_path)),
                ('description', models.TextField()),
                ('contact_no', models.IntegerField(max_length=20)),
                ('rating', models.IntegerField(max_length=5)),
            ],
        ),
    ]
