# Generated by Django 3.1.1 on 2020-09-17 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_hotel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotel',
            name='contact_no',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='rating',
            field=models.IntegerField(),
        ),
    ]
