# Generated by Django 3.1.1 on 2020-09-30 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20200917_2256'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotel',
            name='address',
            field=models.CharField(default='Dhaka', max_length=255),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='contact_no',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='rating',
            field=models.FloatField(max_length=10),
        ),
    ]
